### ISSUE TITLE
請問return_url要如何設定

### ISSUE THREAD

**Issue by game0519** [madeinfree/ez_allpay#3]
您好,
感謝您的gem在付款上如此的好用
使用在return_url的設定上能否請您提供一些設定教學

感謝您

**Comment by game0519** [comment]
可以參考這一篇
http://webtsai.blogspot.tw/2014/11/rails-ezallpay-gem.html

**Comment by madeinfree** [comment]
感謝您！我會將他們整合起來。

**Comment by madeinfree** [comment]
closed#
