### ISSUE TITLE
請問是不是下架了？？

### ISSUE THREAD

**Issue by FredCHHsu** [madeinfree/ez_allpay#4]
安裝時遇到這個問題
Could not find gem 'ez_allpay (>= 0) ruby' in the gems available on this machine.

直接安裝也有
ERROR:  Could not find a valid gem 'ez_allpay' (>= 0) in any repository

**Comment by madeinfree** [comment]
Sorry~ 此gem沒有上傳至rubygem, 需要下載要在後面加入 git: 位置
gem 'ez_allpay', git: 'https://github.com/madeinfree/ez_allpay.git'

可以參考 http://webtsai.blogspot.tw/2014/11/rails-ezallpay-gem.html 此篇設定 ~
如有問題歡迎提問～
